### PR TITLE
Add test cases and d.ts

### PR DESCRIPTION
**Pull request by whinc**
two commit:
1. Add test cases
    cover more test cases
2. Add d.ts file
    improve the intellScene of editor or IDE who support typescript language service

### CODE REVIEW

**Comment by lemori** [comment]
the api is outdated in `d.ts`

**Comment by lemori** [comment]
btw, test cases and ts are two things, please PR them respectively:)

**Comment by whinc** [comment]
Yes, i should split the PR into two. I forget to checkout a  new branch for the second commit.

when you change the public API, you should keep definition sync with the public API. Others can improve it at any time.

**Comment by whinc** [comment]
please close this PR. I will recreate  two separated PR.

**Pull request closed without merging**
