### PR TITLE
Add definitions

### PR DESCRIPTION
**Pull request by whinc**

### CODE REVIEW

**Comment by lemori** [comment]
Hi, this ts has a few definition error / unmatch.
Please be rigorous next time (both PR and MERGE).

**Comment by erichua23** [comment]
My fault, I haven't check it carefully.

**Comment by whinc** [comment]
The d.ts file is committed 12 days ago. Some definitions may not sync with the newest source tree. I will update it.

**Comment by lemori** [comment]
It's ok, I've fixed :)

**Pull request merged**
